import { afterAll, beforeEach } from "vitest";
import { prisma } from "@common/database/prisma";
import { clearMailRuntimeCache, clearOutbox } from "@common/mailer/mailer";
import { siteAccessService } from "../src/modules/site-access/site-access.service";

beforeEach(async () => {
  clearOutbox();
  clearMailRuntimeCache();
  siteAccessService.clearCache();
  await prisma.siteVisit.deleteMany();
  await prisma.siteAccess.deleteMany();
  await prisma.mailProviderSetting.deleteMany();
  await prisma.mailSettings.deleteMany();
  await prisma.testimonial.deleteMany();
  await prisma.review.deleteMany();
  await prisma.notification.deleteMany();
  await prisma.follow.deleteMany();
  await prisma.contactMessage.deleteMany();
  await prisma.cartItem.deleteMany();
  await prisma.cart.deleteMany();
  await prisma.coupon.deleteMany();
  await prisma.payment.deleteMany();
  await prisma.paymentProviderSetting.deleteMany();
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.serviceOrder.deleteMany();
  await prisma.enrollment.deleteMany();
  await prisma.authToken.deleteMany();
  await prisma.refreshToken.deleteMany();
  await prisma.user.deleteMany();
  await prisma.mediaAsset.deleteMany();
  await prisma.videoAsset.deleteMany();
  await prisma.newsletterSubscriber.deleteMany();
  await prisma.profile.deleteMany();
  await prisma.resume.deleteMany();
  await prisma.experience.deleteMany();
  await prisma.education.deleteMany();
  await prisma.certificate.deleteMany();
  await prisma.project.deleteMany();
  await prisma.blog.deleteMany();
  await prisma.tutorial.deleteMany();
  await prisma.course.deleteMany();
  await prisma.service.deleteMany();
  await prisma.topic.deleteMany();
  await prisma.skill.deleteMany();
  await prisma.field.deleteMany();
});

afterAll(async () => {
  await prisma.$disconnect();
});
