ALTER TABLE "users" ADD COLUMN "imageUrl" TEXT;
ALTER TABLE "users" ADD COLUMN "phone" TEXT NOT NULL DEFAULT '';
ALTER TABLE "users" ADD COLUMN "country" TEXT NOT NULL DEFAULT '';
ALTER TABLE "users" ADD COLUMN "notifyProduct" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "users" ADD COLUMN "notifyMarketing" BOOLEAN NOT NULL DEFAULT false;
